### ISSUE TITLE
Add source map support

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#204]
Right now, the profiler reports javascript functions and line numbers. This makes it harder to interpret profiles for users who have written code in typescript. 

We should add source map support so that profiles can report typescript line numbers and function names.

**Comment by nolanmar511** [comment]
I'm starting to look at this, and for my first attempt, it looks like `__awaiter` functions give back bad line number information (well, no line number information). 
Other line information is looking okay so far.

For example: 
JS location:
```
{ 
  file:
   '/usr/local/google/home/nolanmar/cloud-profiler-nodejs-working/cloud-profiler-nodejs/out/src/profilers/time-profiler.js',
  line: 17,
  column: 54,
  name: '__awaiter' 
}
```
Typescript location:
```
{ 
  file:
   '/usr/local/google/home/nolanmar/cloud-profiler-nodejs-working/cloud-profiler-nodejs/ts/src/profilers/time-profiler.ts',
  line: null,
  column: undefined
 }
```

**Comment by aalexand** [comment]
Could it be since this function is produced by the compiler and does not have a correspondence in the user's source? Should we elide such stack frames from the stacks?

**Comment by nolanmar511** [comment]
Yes -- I think that's it. The function is produced by the compiler so doesn't correspond to the user's source code. 

In some cases it might make more sense if these were excluded. But then there are some stacks that are entirely functions which correspond to compiler-generated functions, like this one:

![image](https://user-images.githubusercontent.com/14046562/43537788-268052e4-9575-11e8-9814-951c3d3949f5.png)

So, we would have to special case when we collapse stacks.

**Comment by aalexand** [comment]
In your example, are all of source locations in that stack missing the line number in the source map?

**Comment by nolanmar511** [comment]
Ah! The source maps I'm using don't give function names -- some of those have line numbers.

Looking at the line numbers I'm seeing, I think it's reasonable to use the function name given by the v8-profiler when no names are returned. 

Then, for frames where the file name indicates we would expect to have line information, but we don't we can collapse those frames into their parents.

So, I would want to collapse everything in grey in this profile into its parent, except for the top most frames (top being root).

![image](https://user-images.githubusercontent.com/14046562/43614612-fd8f7c08-9668-11e8-96f1-f8d0e4d53979.png)

Does this seem like the right thing to pursue? I think being able to collapse samples into the parent node will involve some changes to profile serialization which I haven't thought out fully yet.

**Comment by ofrobots** [comment]
Should we be collaborating (sharing code?) with the devtools team that probably has to deal with the same concerns.

/cc @ak239 @a1ph because there are not enough Alexe[iy]'s on this issue.

**Comment by ofrobots** [comment]
For some context, DevTools and [ndb](https://npm.im/ndb) do some blackboxing to collapse stack traces. That code – or at least the business logic – is probably relevant here and can be reused?

**Comment by aalexand** [comment]
Yes, I don't see why we shouldn't do the same thing as Devtools do.

**Comment by nolanmar511** [comment]
Non-grey "(anonymous)" and "__awaiter" functions were from a module that's installed which we don't have source maps for. 
I'll look at the DevTools stuff.

**Comment by nolanmar511** [comment]
Opened #390 as a follow-up to this. 

Closing this, since it was added in #268
