### ISSUE TITLE
Remove hack for determining server-specified retry backoff

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#250]
Once  googleapis/nodejs-common#172 it will be possible to revert #249.

**Comment by aalexand** [comment]
@nolanmar511 Curious - any progress on the upstream bug?

**Comment by aalexand** [comment]
@nolanmar511 A ping on this - was there progress upstream?

**Comment by nolanmar511** [comment]
I asked again about progress on the upstream bug, but no progress yet.

**Comment by aalexand** [comment]
@nolanmar511 @JustinBeckwith Any update?

**Comment by JustinBeckwith** [comment]
Hey folks - this has been fixed. Apologies for the delay here.
