### ISSUE TITLE
CircleCI is getting slow.

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#292]
CircleCI builds seem to be taking longer. 

I was looking at the builds which our tests were queued behind and a saw this message:
```
This build is running under GoogleCloudPlatform's plan which provides 7 containers, plus 3 additional containers available for free and open source projects. Add Containers to run more builds concurrently.
```

Our builds were queued behind builds for GoogleCloudPlatform/google-cloud-java and GoogleCloudPlatform/google-cloud-python.

What's the right thing to do here?

**Comment by aalexand** [comment]
We should probably figure out the admin(s) for GoogleCloudPlatform and contact them asking to raise the capacity of the builders here, but to do that it would be good to quantify "slow" - i.e. what it used to be and what it's now. Can we get numbers like that?

**Comment by JustinBeckwith** [comment]
Greetings folks!  We've most of the way through the process of converting our other node.js repos over to kokoro.  It's been much faster, and more reliable.  @kinwa91 should be able to provide details :)

**Comment by aalexand** [comment]
@nolanmar511 could you talk to @kinwa91 ?

**Comment by nolanmar511** [comment]
@kinwa91 -- Looks like the kokoro tests may have been enabled again?
Is this expected? Should they be passing?

This repo already uses kokoro, so it has a webhook set-up. It will start running kokoro tests as soon as the configurations exist.

**Comment by aalexand** [comment]
@JustinBeckwith We haven't heard anything from @kinwa91. What's the path forward here? Is there a better owner?

**Comment by JustinBeckwith** [comment]
So ....  I don't think this uses circleci anymore!
