### ISSUE TITLE
Only admins can merge commits?

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#334]
aalexand wasn't able to merge a commit. It seems like only admins can merge commits right now. 

I think it's related to our branch protection rules for master, which has this box checked:
![image](https://user-images.githubusercontent.com/14046562/48633424-202d7f00-e978-11e8-86e8-594a5337130a.png)

If we uncheck this box, would people with write access (but not without write access) be able to merge? Any ideas on the best to work around this? Or should I just add anyone who we want to be able to merge commits as an admin?

**Comment by JustinBeckwith** [comment]
oif.  Not sure how that happened.  I made both you and @aalexand admins on the repo, and disabled that setting.  Apologies for the trouble!
