### ISSUE TITLE
What to do about @types dependencies that aren't in devDependencies

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#336]
Typescript modules will not compile without @types/console-log-level and @types/semver modules:
https://sponge.corp.google.com/target?id=3c7a9b78-a7be-45f7-be4b-80b7cc99afa1&target=cloud-profiler/nodejs-agent/presubmit

**Comment by JustinBeckwith** [comment]
There are really two ways to go about this:
1. Don't expose other modules interfaces publicly
2. Ship the `@types` package in the `dependencies` section

1 is ideal, sometimes 2 happens 🤷‍♂️

**Comment by ofrobots** [comment]
IMO, 2 can be avoided in most situations, as here.
