### ISSUE TITLE
Line number information is lost with inlining

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#348]
Related to #19
I'm trying to use the accurate line information feature, and it seems like I'm losing line number information when inlining is enabled.

I'm using the latest version of Node 11.
This is the script I used: [busybench-line-nums.txt](https://github.com/googleapis/cloud-profiler-nodejs/files/2631434/busybench-line-nums.txt)
I used profiling agent in PR #258 

With --noturbo-inlining
![image](https://user-images.githubusercontent.com/14046562/49261796-7975c380-f3f8-11e8-8ca2-677f7fa1dad7.png)

Without --noturbo-inlining
![image](https://user-images.githubusercontent.com/14046562/49261760-66fb8a00-f3f8-11e8-9db2-c3e5c5d33a59.png)

@psmarshall -- Is this expected?

**Comment by psmarshall** [comment]
It looks like this happens when we do nested inlining. e.g. in your example, `f2` seems to have correct line numbers, but `f3` has none at all. V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=8575

**Comment by nolanmar511** [comment]
I've verified that this is fixed in latest version of v8-canary.

Thanks peter for this fix!
