### ISSUE TITLE
system-tests grpc-js fail

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/cloud-profiler-nodejs#403]
This library does not use gax so should not have system tests grpc-js at all, but if we add that task here to make the setup similar, its configuration must be fixed. Right now the task is failing immediately with

```
[16:37:46] [ID: 5735578] Build finished after 1 secs, exit value: 0
[16:37:46] 
[16:37:46] 
[16:37:46] Command done in 10 seconds
[16:37:49][ERROR] Failed to get build config
com.google.devtools.kokoro.config.ConfigException: Couldn't find build configuration under /tmp/workspace/workspace/cloud-devrel/client-libraries/nodejs/continuous/googleapis/cloud-profiler-nodejs/node8/system-test-grpcjs/src/github/cloud-profiler-nodejs/.kokoro/continuous/node8.
```

@kinwa91 can you please take a look and fix? Thanks!

**Comment by JustinBeckwith** [comment]
@kinwa91 bumping the pri on this one - too many failing tests floating about :0
