### ISSUE TITLE
Agent fails to create profiles because it cannot determine instance name

### ISSUE THREAD

**Issue by kalyanac** [googleapis/cloud-profiler-nodejs#488]
Profiler agent is unable to create profiles because it cannot determine instance name. It cannot determine instance name because it, through another module, tries to read the wrong path on the metadata server. 

```
E  @google-cloud/profiler Failed to create profile, waiting 22m 7.9s to try again: Error: Unexpected error determining execution environment: Unsuccessful response status code. Request failed with status code 404
```
Here is associated HTTP request:

```
textPayload:  "[2019-05-17T19:11:36.541Z] "GET /computeMetadata/v1/instanceHTTP/1.1" 404 NR 0 0 0 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" "ffdd47d2-c97d-4a1b-8f73-9780b8f5ee2d" "metadata.google.internal." "-" - - 169.254.169.254:80 10.4.0.30:54716
```

Note that the request is invalid and returns 404 as expected.
`
"GET /computeMetadata/v1/instanceHTTP/1.1" 
`
The correct request should be the following with the header set to HTTP/1.1
`
"GET /computeMetadata/v1/instance/name" 
`

I attempted to root cause where the request is originating from and I think it is in [google-auth-library-nodejs](https://github.com/googleapis/google-auth-library-nodejs)

Tested Environment:
GKE + Istio
Istio config allows egress to the GCE metadata server at 169.254.169.254

**Comment by nolanmar511** [comment]
So, this instance is set [here](https://github.com/googleapis/cloud-profiler-nodejs/blob/50a6f4eb0acb98611bde89bdc3cc57743d083070/ts/src/index.ts#L125), and calls [this](https://github.com/googleapis/cloud-profiler-nodejs/blob/50a6f4eb0acb98611bde89bdc3cc57743d083070/ts/src/index.ts#L36-L39) function. 

So, I think it's coming from [`gcp-metadata`](https://www.npmjs.com/package/gcp-metadata)

**Comment by nolanmar511** [comment]
I'm first going to check if `const res = await gcpMetadata.instance('name');`  is the right way to get the instance name (it may not be).

**Comment by nolanmar511** [comment]
There's another possibility. Instance name and zone are fetched at the beginning.

If the metadata server isn't ready when we query the metadata server, then the instance wouldn't be set (per [this line](https://github.com/googleapis/cloud-profiler-nodejs/blob/50a6f4eb0acb98611bde89bdc3cc57743d083070/ts/src/index.ts#L128) we ignore errors which occur when we fail to get the instance name or zone, since this generally would indicate that one is running locally or on an environment w/o a metadata server).

**Comment by nolanmar511** [comment]
Sorry, one clarification. Is the "associated HTTP request" associated with the attempt to query the metadata server, not with the failed CreateProfile request?

**Comment by kalyanac** [comment]
> Sorry, one clarification: the "associated HTTP request" associated with the attempt to query the metadata server, not with the failed CreateProfile request?

This is the query to the metadata server, not CreateProfile request
