### ISSUE TITLE
Add support for node v12

### ISSUE THREAD

**Issue by mike-marcacci** [googleapis/cloud-profiler-nodejs#490]
I'm sure this is already somewhere in the pipeline, but since v12 is the new LTS we're making plans to move sooner rather than later. Could we get a ballpark estimate for when v12 support might land here?

**Comment by nolanmar511** [comment]
This module depends on a native component which depends on nan.
For now, support for Node 12 is blocked by https://github.com/nodejs/nan/issues/849.

**Comment by mike-marcacci** [comment]
Just to follow up, the upstream dependency is now closed, and nan is stable on v12.

**Comment by nolanmar511** [comment]
@jkwlui -- Is unit testing with Node 12 ready?

Basically, does the trampoline image "gcr.io/cloud-devrel-kokoro-resources/node:12-user" exist?

**Comment by nolanmar511** [comment]
@JustinBeckwith  -- Do you know if unit testing for node 12 is ready?

**Comment by JustinBeckwith** [comment]
We just haven't got there yet.  Last time I checked, we had real problems with `nock`, which we use heavily.  We are tracking this over here:
https://github.com/googleapis/google-cloud-node/issues/2923

**Comment by Maxpain177** [comment]
Any updates?

**Comment by nolanmar511** [comment]
[pprof](https://www.npmjs.com/package/pprof), which is the module @google-cloud/profiler uses to interact with V8's profilers, does have pre-built binaries available for Node 12. So, you should be able to experiment with using Node 12 and cloud-profiler-nodejs. 

But, we're still blocked on unit testing for this repo by googleapis/google-cloud-node#2923.

**Comment by rokerkony** [comment]
any upgrade on this?

**Comment by nolanmar511** [comment]
We've finished adding unit testing with Node 12 for this repository.
I'm planning to release this week.

**Comment by nolanmar511** [comment]
This was fixed with v3.0.0
