### ISSUE TITLE
investigate why release-please is throwing exception

### ISSUE THREAD

**Issue by bcoe** [googleapis/cloud-profiler-nodejs#515]
to be consistent with our release process for other Node.js repos, we should move to using the automated release-please tool.

Currently it appears that the tool is running, but failing on the final step.

**Comment by nolanmar511** [comment]
@bcoe -- Where is release-please documented? I'm not familiar with it.

**Comment by bcoe** [comment]
the [repo is here](https://github.com/googleapis/release-please), it's something you get for free with `.kokoro` hoever, it simply grooms a release-pr, similar to what you'd get running `releasetool` (but automatic based on conventional commit messages)... this is the first repo I've seen the tool fail on, which makes me think it's a permission issue.
