### ISSUE TITLE
Unit tests with Node 13?

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#585]
Right now, we run unit tests with Node 8, 10, and 12.

@bcoe, @JustinBeckwith -- Is there planned support for unit tests with Node 13?

**Comment by bcoe** [comment]
@nolanmar511 I'm open to adding 13, I think we have 3 more months until 14?, but I'd like to take care of updating the testing matrix when we drop Node 8; which I'm hopeful will be mid-way through February.

**Comment by nolanmar511** [comment]
Node version changes are somewhat higher risk for this module, because of it's native dependency that relies on V8.

I'd like to add integration tests with Node 13, but I'd prefer to add integration tests and unit tests at the same time (for ease of debugging). 

Adding just integration tests for Node 13 might be my best choice, but it is somewhat complicating. Our integration test is currently written with the assumption that https://github.com/google/pprof-nodejs has prebuilt binaries for the tested Node version. We use the same trampoline images that are used here in https://github.com/google/pprof-nodejs, and I'm not excited about releasing a pre-built binary for Node 13 when we don't have unit tests for with pprof-nodejs.

**Comment by JustinBeckwith** [comment]
I think we're here, right?
https://github.com/googleapis/cloud-profiler-nodejs/blob/master/.github/workflows/ci.yaml#L12

**Comment by nolanmar511** [comment]
Yep!
I'll close this; it's resolved.
