### ISSUE TITLE
Drop support for Node 8

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#591]
We'd like to drop support for Node 8 before releasing v4.0.0, because we would like to reduce the number of major version changes for this module. 

@bcoe  and @JustinBeckwith -- At what point in time will we be able to drop Node 8?

**Comment by bcoe** [comment]
@nolanmar511 I have a meeting Thursday to discuss with folks on the serverless team, my hope was that we could coordinate with cloud functions promoting Node 10 to GA.

**Comment by nolanmar511** [comment]
@bcoe -- Any updates on the likely timeline for dropping support for Node 8?

**Comment by bcoe** [comment]
@nolanmar511 we're still aiming for mid to late Feb, I will help make sure we have the appropriate testing environments configured for `cloud-profiler-nodejs` :ok_hand:
