### ISSUE TITLE
Windows tests are failing (or flaking)

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/cloud-profiler-nodejs#593]
Looking at https://github.com/googleapis/cloud-profiler-nodejs/pull/592, I can't imagine why that would cause the Windows tests to fail.

**Comment by nolanmar511** [comment]
Looking in [fusion](http://fusion/projectanalysis/summary/KOKORO/prod%3Acloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fcloud-profiler-nodejs%2Fwindows%2Ftest?search_pattern=presubmit%2Fgoogleapis%2Fcloud-profiler-nodejs%2Fwindows%2Ftest&include_inactive_projects=false), tests started failing on Jan 21, when the tested Node version switched from v8.9.1 and v10.15.3 to v12.14.1.

I'll take a look.
