### ISSUE TITLE
Version 4.0.1 has a tag, but no package on npm

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/cloud-profiler-nodejs#669]
Looking at this rollback PR here:
https://github.com/googleapis/cloud-profiler-nodejs/pull/662

The tag was created by this release PR here:
https://github.com/googleapis/cloud-profiler-nodejs/pull/635

But there is no `4.0.1` here:
https://www.npmjs.com/package/@google-cloud/profiler

**Comment by bcoe** [comment]
I don't know what happened here, publish bot removed the tags as if it was published but it never showed up on npm.

[4.0.2](https://www.npmjs.com/package/@google-cloud/profiler/v/4.0.2) has now been published successfully.

I believe this should also make synthtool start working in the morning, if my hypothesis is correct see: #663.
