### ISSUE TITLE
Enable Profiler with Node 14 and later versions of Node 12 once memory leak is fixed.

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#700]
See https://github.com/googleapis/cloud-profiler-nodejs/issues/697 for more information on memory leak.

**Comment by PuKoren** [comment]
Hello. Should this be closed? From the last commits it seems that the support for node 14 has been enabled again, but this issue leave me with a doubt

**Comment by nolanmar511** [comment]
Yes, sorry for the delay in closing this issue. This was fixed with release of Node 14.
