### ISSUE TITLE
@google-cloud/profiler Failed to initialize SourceMapper

### ISSUE THREAD

**Issue by patrickmdixon** [googleapis/cloud-profiler-nodejs#750]
#### Environment details

  - OS: linux-alpine
  - Node.js version: 12.22.1
  - npm version: 6.13.7
  - `@google-cloud/profiler` version:

We've recently installed Profiler in one of our services, and are getting the following error on process startup:

`@google-cloud/profiler Failed to initialize SourceMapper. Source map support has been disabled: Error: An error occurred while processing the source map filesError: An error occurred while reading the sourceMap file /opt/tempus/code/dist/orderhub-shared-tests/ihc-stain.spec.js.map: Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer`

What do we need to do to resolve this source mapping error?

**Comment by amchiclet** [comment]
Sorry for the delay. I've finally been able to prioritize this and just wanted to let you know that I'm looking into this now.

**Comment by amchiclet** [comment]
I will give this a couple more days, then close this as non-reproducible. If you can provide us more information to reproduce the problem, I can look further into it.
