### ISSUE TITLE
@google-cloud/profiler was released, despite failing continuous Kokoro tests

### ISSUE THREAD

**Issue by nolanmar511** [googleapis/cloud-profiler-nodejs#787]
Following https://github.com/googleapis/cloud-profiler-nodejs/issues/245 (in which a change to @google-cloud/common broke server-specified backoffs for this agent) we added a continuous Kokoro integration test to validate that the agent respects server-specified backoffs. Because this E2E test is long-running (the test can't be completed in less than 45 minutes), this test is run only as a continuous Kokoro integration test. Still, this test is important (if server-specified backoffs aren't WAI, a service with a large number of replicas running with profiler enabled will likely start hitting quotas and experiencing higher overhead because too many requests to create profiles are being sent).

This test started failing (with both v4.1.6 and v4.1.7), but it looks the Node.js agent was still released. Is there a way to block auto-release of the Node.js agent on a continuous Kokoro test?

**Comment by bcoe** [comment]
I have created an internal tracking ticket for this, as it relates to the release infrastructure as a whole vs., just profiler.
