### ISSUE TITLE
Node v16 Support

### ISSUE THREAD

**Issue by Skitelman** [googleapis/cloud-profiler-nodejs#823]
It is unclear from your [documentation](https://cloud.google.com/profiler/docs/profiling-nodejs#cloud-console) if you support profiling apps running Node 16.0.0 or higher running on the 16.x branch. Do you know if you support Node v16 profiling and if not, do you know when you will?

**Comment by amchiclet** [comment]
Yes, it is the team's intention to support node v16.

Updating the tests to test against node 16 is on my things to do. I hope to work on this within 1-2 weeks, but can't really commit to it because there are other things on my plate now.

Looks like the document also needs to be updated; thanks for pointing that out.

**Comment by TJB-99** [comment]
Node v16 support would be really great. Is there any update on this?

**Comment by amchiclet** [comment]
I made some progress updating some tests, but I'm not there yet.

The work includes deprecating old versions of Node too, so it's a bit more than I originally expected.

**Comment by weyert** [comment]
Any news on the progress of supporting Node 16? Are you planning to also support Node 18? As it's expected to be LTS on 2022-10-25

**Comment by amchiclet** [comment]
Sorry it's taking a while. I'll try to pick this up if I have some available cycles.

Adding support for node 16 should be straightforward. For node 18, it's more [complicated](https://github.com/google/pprof-nodejs/issues/170#issuecomment-1163210123).

**Comment by weyert** [comment]
Any news on the progress? Isn't now February 2023 and I am not sure if it is supported or not.

**Comment by antonio0** [comment]
Does it support Node 20? It's going to be the new LTS in a month

**Comment by aabmass** [comment]
Node 20 is already supported. If you're seeing a specific issue, please open a new bug with details. I am making another release now and will update the docs to make this clear.
