### ISSUE TITLE
Cloud Profiler on Cloud Run

### ISSUE THREAD

**Issue by edriang** [googleapis/cloud-profiler-nodejs#856]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi there! I wanted to check how can I have Cloud Profiler running with my Cloud Run instances.

I've followed the steps to integrate, but I'm getting the following error (seeing this in Cloud Logger):
`Failed to fetch name from metadata: Error: Unsuccessful response status code. Request failed with status code 404`

I also tried to follow the steps outlined [here](https://github.com/googleapis/cloud-profiler-nodejs#running-elsewhere); I've provided the `projectId` and `credentials` field, but the result is the same.

For the credentials, I've created a Service Account, and assigned the `Cloud Profiler Agent` and `Cloud Profiler User` roles.

I couldn't find any guide or example to integrate Cloud Profiler with Cloud Run, but I would imagine it is certainly possible (or at least it should following the "run elsewhere" steps).

Any idea about this? What else should I try? Thanks in advance

**Comment by aabmass** [comment]
> `Failed to fetch name from metadata: Error: Unsuccessful response status code. Request failed with status code 404`

Sounds like the profiler is trying to query a [metadata server](https://cloud.google.com/compute/docs/metadata/overview) but it doesn't exist in Cloud Run. Try setting these fields in the config to avoid hitting the metadata server: https://github.com/googleapis/cloud-profiler-nodejs/blob/f0ef65053dc285f317106373efa089e00f105b0c/src/index.ts#L129

That said, YMMV with Cloud Run as its not officially supported. You may need to turn on [always on cpu allocation](https://cloud.google.com/blog/products/serverless/cloud-run-gets-always-on-cpu-allocation) but I'm really not sure. Hope that helps.

**Comment by hspak** [comment]
FWIW, I'm able see profiles in GCP with with a nodejs web server running in Cloud Run without issues. I just set it up yesterday.

- nodejs version: 18
- @google-cloud/profiler version: 5.0.3
- snippet
```ts
    require('@google-cloud/profiler')
      .start({
        serviceContext: {
          service: 'my-service',
          version: '1.0.0',
        },
      }) 
```
